### ISSUE TITLE
Make BERT (i.e. transformer) work

### ISSUE THREAD

**Issue by awf** [microsoft/knossos-ksc#360]
Target: demonstrate the power of Knossos on BERT.  
It's a long haul, but some components that may be involved:

- [ ] Port http://nlp.seas.harvard.edu/2018/04/03/attention.html to TorchScript: BERT.py
- [ ] Transform to Knossos IR: BERT.py -> BERT.ks
- [ ] Pass through AD: BERT.ks -> BERT-AD.ks
- [ ] Pass through RLO [see below]
- [ ] Compile to C++ (CPU), benchmark
- [ ] Compile to MLIR/ONNX, benchmark

And "Pass through RLO" has its own subgoals
- [ ] Pass through RLO, no crashes
- [ ] Pass through RLO, "expert" rewriter
- [ ] Pass through RLO, "restricted rules" rewriter
- [ ] Pass through RLO, learned general rewriter
- [ ] Pass through RLO, above 3 with memory/communications cost model
