### ISSUE TITLE
TorchScript models pass through KSC and are fast

### ISSUE THREAD

**Issue by awf** [microsoft/knossos-ksc#369]
Subtasks:

- [x] GMM in TS generates correct value #365 
- [x] GMM in TS generates correct gradient  #365 
- [x] GMM in TS gradient runs in ADbench [ADBench#197](https://github.com/microsoft/ADBench/pull/197) [ADBench#198](https://github.com/microsoft/ADBench/pull/198)
- [ ] BERT in TS generates correct value
- [ ] BERT in TS generates correct gradient
- [ ] GMM in TS goes through KSC->C++->EXE, correct value
- [ ] GMM in TS goes through KSC->C++->EXE, correct gradient
- [ ] GMM in TS goes through KSC->C++->EXE, gradient in ADbench
- [ ] GMM in TS goes through KSC->C++->EXE, correct value, reasonably performant
- [ ] GMM in TS goes through KSC->C++->EXE, correct gradient, reasonably performant
- [ ] GMM in TS goes through KSC->C++->EXE, gradient in ADbench, reasonably performant
- [ ] BERT in TS generates gradient in ADbench
- [ ] BERT in TS goes through KSC->C++->EXE, correct value
- [ ] BERT in TS goes through KSC->C++->EXE, correct gradient
- [ ] BERT in TS goes through KSC->C++->EXE, gradient in ADbench
- [ ] BERT in TS goes through KSC->C++->EXE, correct value, reasonably performant
- [ ] BERT in TS goes through KSC->C++->EXE, correct gradient, reasonably performant
- [ ] BERT in TS goes through KSC->C++->EXE, gradient in ADbench, reasonably performant
