### ISSUE TITLE
Implement "classic" reverse mode (CRM) via single-use form (SUF)

### ISSUE THREAD

**Issue by awf** [microsoft/knossos-ksc#377]
Our "linear map" implementation of reverse mode yields bad code (#376) and also #58.   
We assume "classic" reverse mode (CRM) would be better.  
But CRM needs mutation (?)
So we need SUL:

- [x] KS->KS_SUF transformation
    - [x] Implement tuple pattern matching #185 
    - [x] Introduce dup, elim
    - [x] Implement KS->KS_SUF
- [ ] KS_SUF->Reverse mode.  Forward pass emits result and bog, reverse pass takes bog.
    - [x] Programs where `if` branches have same type of BOG. At least one test case/example?  e.g. `xsinx`, `relu`
    - [x] Programs where `if` branches have different type of BOG, union as tuple.
    - [x] Implement `build` 
    - [x] Fix codegen so `setAt`/`incAt` is fast inplace.
    - [ ] Is rev$matmul efficient?  Prediction: no, because cubic bog.
        - [ ] Benchmark rev$matmul under LMAD, SUAD -- sizes up to 1 minute's worth of computation
    - [x] Does GMM work yet?
    - [ ] Implement union types #247 
    - [ ] Implement `if` for non-matching BOGs using Union types
    - [x] Does GMM work yet?
    - [x] Benchmark GMM
    - [ ] Implement cumsum and benchmark
    - [ ] Implement recursive prod
- [ ] Performance: GMM is as fast as existing AD
    - [ ] Implement pass: if SUP, replace all incAt/dup with inplaceIncAt, inplaceDup
    - [x] Make smaller BOGs - remove all units
    - [ ] Make smaller BOGS - write doc on what makes bogs big, with examples?
    - [ ] Make smaller BOGs - removal of  [trivial functions of] (function inputs)?
    - [ ] Make smaller BOG - elim bog is shape of x, not x
      - [x] Make shape transform an opt #739 
      - [ ] Change definition of ``shape :: Tensor D <Scalar> -> (Tuple Int ....)`` #745 
      - [ ] Use shapes in elim bog #707 
    - [ ] inplace_add in map https://github.com/microsoft/knossos-ksc/issues/799
- [ ] Recursion and other looping
    - [x] Implement `ifold`
    - [ ] Implement `ifold` with copydown -- benchmark
    - [ ] Implement recursive types #247
    - [ ] Show that recursive prod is correct and asymptotically efficient  

Additions, Feb 2021:
- [x] Needed: identify from rev$ functions other than by call-site type #551 
- [x] Needed: gdef #512 
- [ ] gelu : Tensor n Float -> Tensor n Float
  - [x] map
    - [x] Introduce map primitive to KS, analogous to build/ifold
    - [x] Define suffwdpass, sufrevpass for map
    - [ ] Extend map for LM AD
- [ ] Composition of gelu and Add: https://github.com/microsoft/onnxruntime/pull/2360
- [ ] Composition of gelu and MatMul.

Additions, May 2021:
- [ ] vrelu3: identify optimisation opportunities and use them to prioritise/add work above
- [ ] `map$Os` vs `map$Ot` (see [Checkpointing](https://microsoft.sharepoint.com/teams/KnossoswasCoconut/_layouts/OneNote.aspx?id=%2Fteams%2FKnossoswasCoconut%2FShared%20Documents%2FKnossos&wd=target%28Diary.one%7C4F1DED29-6176-439F-B36B-50A0E2D04B11%2FCheckpointing%7C8A76EDFE-7FE5-494A-9DA3-CC444326A143%2F%29))
