### ISSUE TITLE
Good end-to-end Windows support

### ISSUE THREAD

**Issue by cgravill** [microsoft/knossos-ksc#678]
We want to have good end-to-end support for Windows from PyTorch through Knossos, and returned optimised functionality.

We're starting from a decent position as we've had builds including Windows for parts of the project.

- [x] build PyTorch extension with KSC generated code with [MSVC](https://visualstudio.microsoft.com/vs/features/cplusplus/) #652
  - [ ] allow ksc to directly build with MSVC as well
- [x] enable running or skip Python tests on Windows #662 
- [x] run current TS2K automated test on Windows #669 #665 
  - [x] out of memory issues on multiple tests - likely to apply to Linux as well but not triggered #679 mitigated with #706
- [x] run on a current version of PyTorch - 1.8 failures #659 #683 
- [x] nightly preview builds of TS2K to ensure the PyTorch C++ keeps working for our usage #669 
- [ ] contribute documentation fixes back to PyTorch to improve overall C++ PyTorch on Windows
