### ISSUE TITLE
Epic: Benchmarking and dashboard

### ISSUE THREAD

**Issue by awf** [microsoft/knossos-ksc#725]
We would like to be able to measure speed improvements build-over-build in KSC.  To do so we need an evaluation framework with these features

  - [x] I can define a benchmark function `foo` in python module `a/b/d/bar.py`.   That benchmark function comes with PyTorch reference implementations, and sample inputs. (#645)
  - [x] There is infrastructure, a script `run-benchmarks`, which manages 
    - [ ] running
      - [x] function (#645)
      - [x] gradient (#645)
      - [ ] jacobian
    - [ ] correctness checking
      - [x] function (#645)
      - [ ] gradient
      - [ ] jacobian
    - [x] timing (#645)
    - [ ] plotting
  - [ ] I can compare results build-over-build as a
    - [x] table (#645, function only)
    - [x] plot (#645, function only)
